#config_version=5
mode:
  start_events: start_mode_lane_rotate, ball_started
  stop_events: stop_mode_lane_rotate, ball_will_end

shots:
  r_h:
    switch: s_h
    profile: rotate_profile
    show_tokens:
      led: l_inlane_l
  r_o:
    switch: s_stationary_o
    profile: rotate_profile
    show_tokens:
      led: l_target_l
  r_u:
    switch: s_stationary_u
    profile: rotate_profile
    show_tokens:
      led: l_target_mid_l
  r_s:
    switch: s_stationary_s
    profile: rotate_profile
    show_tokens:
      led: l_target_r
  r_e:
    switch: s_e
    profile: rotate_profile
    show_tokens:
      led: l_inlane_r
      
show_player:
#  inout_lane_group_hit_complete:


shot_groups:
  rotate_group:
    shots: r_h, r_o, r_u, r_s, r_e
    reset_events: rotate_group_hit_complete
    rotate_left_events: s_flipper_left_active
    rotate_right_events: s_flipper_right_active

shot_profiles:
  rotate_profile:
    states:
      - name:
        show: off
      - name: hit
        show: on

variable_player:
  rotate_group_hit_complete:
    score: 1000
