#config_version=6
mode:
  start_events: start_mode_launch_shows, waiting_for_launch_press
  stop_events: start_mode_launch_shows, ball_started
  priority: 200
  
slide_player:
  mode_launch_shows_started: 
    launch:
      action: queue_first
      priority: 200
    
  

  
show_player:
  mode_launch_shows_started.1: launch_tilt
  mode_launch_shows_started.2: launch_lights
    
