#config_version=6

mode_settings:
    bonus_entries:
        - entry: b_switches_hit
          text: "Switches Hit:"
          player_score_entry: v_switches_hit
          score: 100
        - entry: b_house_completes
          text: "H-O-U-S-E Completes:"
          player_score_entry: v_house_completes_bonus
          reset_player_score_entry: true
          score: 5_000

slide_player:
    mode_bonus_started: bonus
    bonus_start:
        bonus:
            action: update
            tokens:
                entry: initial
    bonus_entry:
        bonus:
            action: update