#config_version=6
mode:
  start_events: mult_3_ball_start
  stop_events: mult_3_ball_stop, multiball_3_ball_multiball_ended
  events_when_started: fleshy_qualify_stop
  events_when_stopped: fleshy_qualify_start
  priority: 190
  
multiballs:
  3_ball_multiball:
    ball_count: 3
    shoot_again: 0s
    start_events: mode_mult_3_ball_started
    
ball_saves:
  3_ball_save:
    active_time: 15s
    hurry_up_time: 3s
    timer_start_events: balldevice_bd_trough_ejecting_ball
    auto_launch: true
    balls_to_save: -1
    disable_events: mode_hurryup_tilt_started
show_player:

  
  ball_save_3_ball_save_timer_start.1:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: pink
  ball_save_3_ball_save_timer_start.2:
    mult_fleshy_start_show:
      loops: 0
  ball_save_3_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 8
      show_tokens:
        lights: l_shoot_again
        color: pink
  ball_save_3_ball_save_disabled:
    3_ball_save: stop
    
shots:

  r_right_orbit_3_ball:
    hit_events: ss_right_orbit_hit
    profile: sp_3_ball_jp
    restart_events: mult_flesh_jp_reset
    show_tokens:
      led: l_arrow_loop
      led2: l_circle_loop
  r_pop_fleshy:
    switch: s_pop
    restart_events: mult_flesh_jp_reset


shot_profiles:
  sp_3_ball_jp:
      block: true
      states:
      - name: 
        show: "3_ball_jp"
        
variable_player:
  r_ramp_l_fleshy_sp_fleshy_jp_hit:
    threeballmultiplier: 3
  r_right_orbit_3_ball_hit:
    score:  current_player.threeballmultiplier * 100 * current_player.balls_in_play
    3ballmultiplier:
      int: 1
      action: set
  mode_mult_3_ball_started:
    house_completes:
      int: 0
      action: set
      
event_player:

  multiball_3_ball_multiball_started:
    - stop_modes_during_multiball
  multiball_3_ball_multiball_ended:
    - start_modes_after_multiball



    