#config_version=6
# in your mode
mode:
  start_events: ball_started
ball_saves:
  ball_save_ball_save:
    active_time: 7s
    hurry_up_time: 3s
    timer_start_events: balldevice_bd_trough_ejecting_ball
    auto_launch: true
    balls_to_save: 1
show_player:
  ball_save_ball_save_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: red
  ball_save_ball_save_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 8
      show_tokens:
        lights: l_shoot_again
        color: red
  ball_save_ball_save_ball_save_disabled:
    ball_save: stop