#config_version=6
mode:
  start_events: mult_fleshy_start
  stop_events: mult_fleshy_stop, multiball_fleshy_multiball_ended
  priority: 200
  
multiballs:
  fleshy_multiball:
    ball_count: 2
    shoot_again: 0s
    start_events: mode_mult_fleshy_started
    
ball_saves:
  ball_save:
    active_time: 20s
    hurry_up_time: 3s
    timer_start_events: balldevice_bd_trough_ejecting_ball
    auto_launch: true
    balls_to_save: -1
    disable_events: mode_hurryup_tilt_started
show_player:

  mult_flesh_jp_reset:
    knife_breathe_super:
      loops: 0
      speed: 100
  
  ball_save_ball_save_timer_start.1:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: red
  ball_save_ball_save_timer_start.2:
    mult_fleshy_start_show:
      loops: 0
  ball_save_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 8
      show_tokens:
        lights: l_shoot_again
        color: red
  ball_save_ball_save_disabled:
    ball_save: stop
    
shots:
  r_ramp_r_fleshy:
    hit_events: ss_ramp_r_hit
    profile: sp_fleshy_jp
    restart_events: mult_flesh_jp_reset
    show_tokens:
      led: l_arrow_ramp_r
      led2: l_circle_ramp_r
  r_ramp_l_fleshy:
    hit_events: ss_ramp_l_hit
    profile: sp_fleshy_jp
    restart_events: mult_flesh_jp_reset
    show_tokens:
      led: l_arrow_ramp_l
      led2: l_circle_ramp_l
  r_right_orbit_fleshy:
    hit_events: ss_right_orbit_hit
    profile: sp_fleshy_jp
    restart_events: mult_flesh_jp_reset
    show_tokens:
      led: l_arrow_loop
      led2: l_circle_loop
  r_vuk_fleshy:
    switch: s_vuk
    profile: sp_fleshy_jp
    restart_events: mult_flesh_jp_reset
    show_tokens:
      led: l_vuk_arrow_bot
      led2: l_vuk_square_bot

shot_profiles:
  sp_fleshy_jp:
      block: true
      states:
      - name: 
        show: "fleshy_blink"
      - name: jp_hit
        show: "off"
        
variable_player:
  r_ramp_l_fleshy_sp_fleshy_jp_hit:
    score: 2000
  r_ramp_r_fleshy_sp_fleshy_jp_hit:
    score: 2000
  r_right_orbit_fleshy_sp_fleshy_jp_hit:
    score: 2000
  r_vuk_fleshy_sp_fleshy_jp_hit:
    score: 2000

        
shot_groups:
  fleshy_jackpot_group:
    shots: r_ramp_r_fleshy, r_ramp_l_fleshy, r_right_orbit_fleshy, r_vuk_fleshy
        
event_player:
  fleshy_jackpot_group_jp_hit_complete:
    - mult_fleshy_super_begin
  multiball_fleshy_multiball_started:
    - stop_modes_during_multiball
  multiball_fleshy_multiball_ended:
    - start_modes_after_multiball

    