#config_version=6
mode:
  start_events: mult_fleshy_start
  stop_events: mult_fleshy_stop
  priority: 200
  
multiballs:
  fleshy_multiball:
    ball_count: 2
    shoot_again: 0s
    start_events: mode_fleshy_mult_started
    
ball_saves:
  ball_save:
    active_time: 10s
    hurry_up_time: 3s
    timer_start_events: balldevice_bd_trough_ejecting_ball
    auto_launch: true
    balls_to_save: -1
show_player:
  
  ball_save_ball_save_timer_start.1:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: red
  ball_save_ball_save_timer_start.2:
    mult_fleshy_start_show:
      loops: 0
  ball_save_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 8
      show_tokens:
        lights: l_shoot_again
        color: red
  ball_save_ball_save_disabled:
    ball_save: stop

shot_profiles:
  #ramp_l_jp:
    