#config_version=6
mode:
  start_events: mult_fleshy_start
  stop_events: mult_fleshy_stop
  
multiballs:
  fleshy_multiball:
    ball_count: 2
    shoot_again: 0s
    start_events: mode_mult_fleshy_started
    
ball_saves:
  fleshy_save:
    active_time: 10s
    hurry_up_time: 2s
    timer_start_events: mode_mult_fleshy_started
    auto_launch: true
    balls_to_save: -1
show_player:
  fleshy_save_ball_save_timer_start:
    flash_color:
      key: ball_save
      speed: 2
      show_tokens:
        lights: l_shoot_again
        color: red
  fleshy_save_ball_save_hurry_up:
    flash_color:
      key: ball_save
      speed: 4
      show_tokens:
        lights: l_shoot_again
        color: red
  fleshy_save_ball_save_disabled:
    ball_save: stop

shots: